### ISSUE TITLE
requires DNAcopy package

### ISSUE THREAD

**Issue by rosherbal** [francescojm/CRISPRcleanR#3]
Preinstallation of the DNAcopy package is required. This package is available in Bioconductor: https://bioconductor.org/packages/release/bioc/html/DNAcopy.html

**Comment by paolocremaschi** [comment]
Hi Rosa, 
thanks for your note. Since version 2.2.1 we update the dependency list to avoid the need of preinstall DNAcopy.
Regards,
Paolo
