### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rkostadi** [francescojm/CRISPRcleanR#6]
Hi Francesco,
Could you please include a license for the source code to the repo?
e.g. GPL, MIT, Apache, etc.
Thank you,
Rumen

**Comment by francescojm** [comment]
Hi rkostadi,
the license type is specified in the package DESCRIPTION file, and as you will notice it has been updated to MIT since version 2.2.2

**Comment by francescojm** [comment]
The LICENSE file has been now added
